# Site settings
name: Diary
email: bennyRick80@gmail.com
author: Benny Rick
url: 
resume_site: 
github: https://github.com/bennyrick80/
baseurl:
description: Actually, It's my fault!
meta_description: I'm sorry.
motto: It's our wits that make us men.
banner: Wellcome
disqus_shortname: bennyrick80

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: bennyrick80

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

